### ISSUE TITLE
Multiple running of a encode command

### ISSUE THREAD

**Issue by Ninelpienel** [stuxcrystal/yuuno#4]
It’s possible to run the same encode command few times. It will start a new encode session after finishing the old one and overwrite the old file. A function that can suppress this would be nice.

**Comment by stuxcrystal** [comment]
It is. The `%encode`-magic is a line-magic.

```ipython
%encode some_clip COMMAND
%encode another_clip COMMAND
```

**Comment by Ninelpienel** [comment]
I meant when I run the same cell with the same encode line accidentally two times, it will encode with the same line two times in a row.

**Comment by stuxcrystal** [comment]
Yes. This is expected behaviour. _Executing a line twice will cause it to be executed twice_. It's as simple as that.
