### ISSUE TITLE
Not showing the encode console when running multiple sessions at the same time

### ISSUE THREAD

**Issue by Ninelpienel** [stuxcrystal/yuuno#5]
When I want to encode two ore more scripts at once, only the first running encode console will show up. When I start a second or a third one, the console not show up.

**Comment by stuxcrystal** [comment]
Did you check if the second encode command stars running after the first one is finished?

**Comment by Ninelpienel** [comment]
Yes, the second encode is running.

**Comment by stuxcrystal** [comment]
This is expected behavior. All code is executed sequentially.
